#!/bin/bash


##
## autogenerated kannel-972523245068 docker starter
echo "starting kannel-972523245068"
docker run -rm -d --name kannel-972523245068 \
	   -p 15068:13013 \
	   -p 25068:2776 \
	   --device=/dev/ttyUSB0 --cap-add SYS_PTRACE \
           --volume $(readlink -f volumes)/972523245068/kannel/etc/:/etc/kannel \
           --volume $(readlink -f volumes)/972523245068/kannel/log:/var/log/kannel \
           --volume $(readlink -f volumes)/972523245068kannel/spool:/var/spool/kannel \
           kannelplus:2.1

echo "kannel-972523245068 started."
sleep 2s
###########################################################

##
## autogenerated kannel-972522736902 docker starter
echo "starting kannel-972522736902"
docker run -rm -d --name kannel-972522736902 \
	   -p 16902:13013 \
	   -p 26902:2776 \
	   --device=/dev/ttyUSB1 --cap-add SYS_PTRACE \
           --volume $(readlink -f volumes)/972522736902/kannel/etc/:/etc/kannel \
           --volume $(readlink -f volumes)/972522736902/kannel/log:/var/log/kannel \
           --volume $(readlink -f volumes)/972522736902kannel/spool:/var/spool/kannel \
           kannelplus:2.1

echo "kannel-972522736902 started."
sleep 2s
###########################################################


docker ps 
echo "done."
